FADER_CC_START = 12
BUTTON_CC_START = 32

FADER_COUNT = 8
BUTTON_COUNT = 8

# 0-based MIDI channels
TRANSPORT_CHANNEL = 0
BUTTON_CHANNEL = 0
FADER_CHANNEL = 0

# Transport control CC
TRANSPORT_BACKWARD = 115
TRANSPORT_FORWARD = 116
TRANSPORT_STOP = 117
TRANSPORT_PLAY = 118
TRANSPORT_RECORD = 119
TRANSPORT_LOOP = 114

